#!/usr/bin/env python3
"""List every screenshot the documentation is still waiting for.

Each page carries dashed placeholder slots — <figure class="imgslot"> — naming
the file it wants and describing what the picture has to show. This walks them
all and writes SCREENSHOTS.md, so the outstanding work is one file rather than
something you find by scrolling fourteen pages.

    python3 tools/shots.py            # rewrite SCREENSHOTS.md
    python3 tools/shots.py --list     # just print the filenames
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
SHOTS = ROOT / "assets" / "img" / "shots"
OUT = ROOT / "SCREENSHOTS.md"

SLOT_RE = re.compile(
    r'<figure class="imgslot"[^>]*data-shot="([^"]+)"[^>]*>(.*?)</figure>', re.S)
B_RE = re.compile(r"<b>(.*?)</b>", re.S)
SPAN_RE = re.compile(r"<span>(.*?)</span>", re.S)
H2_RE = re.compile(r'<h2[^>]*\sid="([^"]+)"[^>]*>(.*?)</h2>', re.S)
META_RE = re.compile(r'"title":\s*"([^"]+)"')
TAG_RE = re.compile(r"<[^>]+>")


def clean(s: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(TAG_RE.sub("", s))).strip()


# Places the site would be better for a picture, but which carry no placeholder
# because they already hold a designed stand-in. Purely optional.
OPTIONAL = [
    {
        "file": "hero-report-dashboard.png",
        "page": "Home (index.html)",
        "slug": "index",
        "section": "Hero",
        "brief": "The real report's Dashboard at 1440x900, light theme, on a run with a handful "
                 "of failures. The landing page currently draws a CSS schematic of this. Swapping "
                 "in a real screenshot is the single highest-value picture on the site — replace "
                 "the whole <div class=\"mock\"> block in index.html with a <figure class=\"shot\">. "
                 "Take a dark-theme version too if you want it to follow the reader's theme.",
        "kind": "PNG",
        "label": "",
        "have": False,
        "optional": True,
    },
]


def collect() -> list[dict]:
    rows: list[dict] = []
    for path in sorted(CONTENT.glob("*.html")):
        raw = path.read_text(encoding="utf-8")
        m = META_RE.search(raw[:600])
        page_title = m.group(1) if m else path.stem

        # Where each h2 starts, so a slot can be attributed to its section.
        heads = [(mm.start(), clean(mm.group(2))) for mm in H2_RE.finditer(raw)]

        for slot in SLOT_RE.finditer(raw):
            fname = slot.group(1)
            inner = slot.group(2)
            b = B_RE.search(inner)
            span = SPAN_RE.search(inner)
            section = ""
            for pos, title in heads:
                if pos < slot.start():
                    section = title
                else:
                    break
            rows.append({
                "optional": False,
                "file": fname,
                "page": page_title,
                "slug": path.stem,
                "section": section,
                "label": clean(b.group(1)) if b else "",
                "brief": clean(span.group(1)) if span else "",
                "kind": "GIF" if fname.lower().endswith(".gif") else "PNG",
                "have": (SHOTS / fname).exists(),
            })
    return rows


def main() -> int:
    rows = collect()
    if "--list" in sys.argv:
        for r in rows:
            print(("[have] " if r["have"] else "[need] ") + r["file"])
        return 0

    for o in OPTIONAL:
        o["have"] = (SHOTS / o["file"]).exists()
    rows = rows + OPTIONAL

    by_page: dict[str, list[dict]] = {}
    for r in rows:
        by_page.setdefault(r["page"], []).append(r)

    need = [r for r in rows if not r["have"]]
    gifs = [r for r in need if r["kind"] == "GIF"]

    lines = [
        "# Screenshots the documentation is waiting for",
        "",
        "Generated by `python3 tools/shots.py` — do not edit by hand.",
        "",
        f"**{len(need)} outstanding** ({len(gifs)} of them animated) across "
        f"{len(by_page)} page(s).",
        "",
        "## What the filled slots look like",
        "",
        "The nine report tabs are already in, taken from a real 1,589-test run with 21",
        "archived builds. They live in `assets/img/shots/` as lossless WebP at 1800px wide",
        "(a 2x capture of a 900px column), each as a `<base>-light.webp` / `<base>-dark.webp`",
        "pair, and the page shows whichever matches the theme the reader is on:",
        "",
        "```html",
        "<figure class=\"shot shot--themed\">",
        "  <img class=\"shot__light\" src=\"../assets/img/shots/<base>-light.webp\" alt=\"…\"",
        "       width=\"1800\" height=\"926\" loading=\"lazy\" decoding=\"async\">",
        "  <img class=\"shot__dark\" src=\"../assets/img/shots/<base>-dark.webp\" alt=\"…\"",
        "       width=\"1800\" height=\"926\" loading=\"lazy\" decoding=\"async\">",
        "  <figcaption>…</figcaption>",
        "</figure>",
        "```",
        "",
        "Use `<figure class=\"shot\">` with a single `<img>` for anything that does not change",
        "with the theme, and add `shot--narrow` to a crop far taller than it is wide.",
        "",
        "## How to fill one in",
        "",
        "1. Take the picture described below. Serve a generated report and drive it: every",
        "   tab is at `#dashboard`, `#analytics`, `#suites`, `#test-metrics`, `#test-steps`,",
        "   `#archives`, `#screenshots`, `#api-logs` and `#coverage`, and `#themeSwitch`",
        "   toggles the theme. Capture at 2x, in both themes where the shot is of the report.",
        "2. Save it into `assets/img/shots/`, 1800px wide, as lossless WebP.",
        "3. In `content/<page>.html`, replace the whole `<figure class=\"imgslot\">…</figure>`",
        "   block with a `<figure class=\"shot\">` as above.",
        "4. Run `python3 tools/build.py`, then `python3 tools/check.py`.",
        "",
        "The `<filename>` on each row below is the name the slot was written against, not a",
        "rule — the src just has to point at something that exists.",
        "",
    ]

    for page, items in by_page.items():
        slug = items[0]["slug"]
        lines.append(f"## {page}")
        lines.append("")
        if slug == "index":
            lines.append("`index.html` — hand-written, not built from `content/`.")
        else:
            lines.append(f"`content/{slug}.html` → [docs/{slug}.html](docs/{slug}.html)")
        lines.append("")
        for r in items:
            tick = "x" if r["have"] else " "
            tag = " &nbsp;·&nbsp; *optional*" if r.get("optional") else ""
            lines.append(f"- [{tick}] **`{r['file']}`** &nbsp;·&nbsp; {r['kind']}{tag}")
            if r["section"]:
                lines.append(f"  - section: *{r['section']}*")
            if r["brief"]:
                lines.append(f"  - shows: {r['brief']}")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} — {len(need)} outstanding, "
          f"{len(rows) - len(need)} already in place.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
